package goldkit

import (
	"bytes"
	"errors"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"slices"
)

// ErrMultipartClosed is an error returned when adding fields or files to the
// closed [MultiPart] body.
var ErrMultipartClosed = errors.New("multipart body closed")

// MultiPart is a helper for building MIME multipart body.
type MultiPart struct {
	w      *multipart.Writer // Multipart writer.
	body   bytes.Buffer      // The buffer writer writes body to.
	closed bool              // Was the Close method invoked?
}

// NewMultipart returns a new initialized [MultiPart] instance with a custom
// boundary. When a boundary is set to empty string, the boundary will be
// autogenerated.
func NewMultipart() *MultiPart {
	mp := &MultiPart{}
	mp.w = multipart.NewWriter(&mp.body)
	return mp
}

// SetBoundary sets multipart boundary separator.
func (mp *MultiPart) SetBoundary(boundary string) error {
	return mp.w.SetBoundary(boundary)
}

// Boundary returns multipart boundary separator.
func (mp *MultiPart) Boundary() string {
	return mp.w.Boundary()
}

// AddField adds form field with value.
func (mp *MultiPart) AddField(field, value string) error {
	if mp.closed {
		return ErrMultipartClosed
	}
	return mp.w.WriteField(field, value)
}

// AddFile adds file to multipart body.
func (mp *MultiPart) AddFile(field, name string, content io.Reader) error {
	if mp.closed {
		return ErrMultipartClosed
	}
	part, err := mp.w.CreateFormFile(field, name)
	if err != nil {
		return err
	}
	if _, err = io.Copy(part, content); err != nil {
		return err
	}
	return nil
}

// SetContentTypeHeader sets Content-Type header in the given map.
func (mp *MultiPart) SetContentTypeHeader(h http.Header) {
	h.Set("Content-Type", mp.w.FormDataContentType())
}

// Request generates [http.Request] with the specified method and path and
// multipart body based on the current state of the [MultiPart] instance.
// Before generating the request, it calls Close method. The request's
// Content-Type header is automatically set to the multipart form data content
// type. The request's body is parsed as multipart form data with a maximum
// size of 10 MB.
func (mp *MultiPart) Request(method, path string) (*http.Request, error) {
	if err := mp.Close(); err != nil {
		return nil, err
	}
	// Read from a snapshot of the buffer so repeated Request or Body calls
	// still see the full body; httptest.NewRequest drains its reader.
	req := httptest.NewRequest(method, path, bytes.NewReader(mp.body.Bytes()))
	mp.SetContentTypeHeader(req.Header)
	if err := req.ParseMultipartForm(10e6); err != nil {
		return nil, err
	}
	return req, nil
}

// Body returns the copy of the body written through the [MultiPart]. It first
// closes the [MultiPart] to ensure that all writing operations are finished.
// Then it returns the bytes stored in the body buffer.
func (mp *MultiPart) Body() []byte {
	_ = mp.Close()
	return slices.Clone(mp.body.Bytes())
}

// Close finishes the multipart message and writes the trailing boundary end
// line to the body. It may be called multiple times and will not add the
// trailing boundary if the body is empty.
func (mp *MultiPart) Close() error {
	if !mp.closed {
		mp.closed = true
		if mp.body.Len() > 0 {
			return mp.w.Close()
		}
	}
	return nil
}
